import { useClient } from 'next/data-client';
import { Inter } from 'next/font/google'
import './globals.css'
import Cabecalho from '@/components/Cabecalho/Cabecalho'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  useClient();
  
  return (
    <html lang="en">
      <body className={inter.className}>

        <Cabecalho/>

        {children}
      
      <Rodape/>

      </body>
    </html>
  )
}
